### ISSUE TITLE
[Windows] getting 'failed to read file' on fresh clone

### ISSUE THREAD

**Issue by aikeru** [jacobp100/tree-shaking-bootstrap#1]
I get this error when I try to run gulp after doing an npm install from a fresh clone:
![image](https://cloud.githubusercontent.com/assets/1163405/15797551/26ee0b82-29e2-11e6-978a-4fcf4e77bf2e.png)

**Comment by jacobp100** [comment]
Could you try it now? You may need to nuke your node_modules.

**Comment by aikeru** [comment]
I'm still experiencing the issue. I even re-cloned the repo, ran npm install, then gulp.
In case this helps I'm using npm 3.5.3 and node 4.2.2 on Windows 8.1.

**Comment by jacobp100** [comment]
I don’t have access to Windows, so can I be a pain and ask you to check if https://github.com/isaacs/minimatch/issues/78 is still an issue?

**Comment by aikeru** [comment]
I don't mind testing it, but I'm not sure how to setup a valid case to test... Here's a couple things I tried...

![image](https://cloud.githubusercontent.com/assets/1163405/15800273/6b8018e6-2a3a-11e6-8be9-744ab4823602.png)

![image](https://cloud.githubusercontent.com/assets/1163405/15800285/93e209f2-2a3a-11e6-9b3c-54c5466feb3a.png)

**Comment by aikeru** [comment]
Do you have any suggestions on how to create a valid test case?

**Comment by jacobp100** [comment]
~~Can you try again now? (nuke node_modules again)~~

Could you clone https://github.com/jacobp100/get-es-imports-exports, run `npm test`, and let me know the results?

**Comment by aikeru** [comment]
Here's what I got:
![image](https://cloud.githubusercontent.com/assets/1163405/15802373/41b1c5ce-2a75-11e6-92ba-7dfb25581d0c.png)

**Comment by aikeru** [comment]
This is probably what you already know...
I changed index.js in 'get-es-imports-exports' the raw code from lines to 113 or so to the following:

```
    const fileIsExcluded = (0, _fp.isEmpty)(excludeValues) ? (0, _fp.constant)(false) : function (file) {
        console.log('testing file', file);
        let isEx = (0, _fp.some)((0, _fp.cond)([[(0, _fp.includes)('*'), (0, _fp.partial)(_minimatch2.default, [file])], [(0, _fp.constant)(true), (0, _fp.equals)(file)]]), excludeValues);
        console.log('isex', isEx);
      return (0, _fp.some)((0, _fp.cond)([[(0, _fp.includes)('*'), (0, _fp.partial)(_minimatch2.default, [file])], [(0, _fp.constant)(true), (0, _fp.equals)(file)]]), excludeValues);
    };
```

here's what I get back:

```
testing file c:\Projects\tree-shaking-bootstrap\src\index.js
isex false
testing file c:\Projects\tree-shaking-bootstrap\node_modules\react\react.js
isex false
testing file c:\Projects\tree-shaking-bootstrap\node_modules\react-dom\index.js
isex false
testing file c:\Projects\tree-shaking-bootstrap\src\components\Example.js
isex false
testing file c:\Projects\tree-shaking-bootstrap\node_modules\classnames\index.js

isex false
testing file c:\Projects\tree-shaking-bootstrap\styles\bootstrap.m.css
isex false

events.js:141
      throw er; // Unhandled 'error' event
      ^
```

If I add this one extra line, the build succeeds and index.html seems to fire up fine:

```
if(file.indexOf('.m.css') > -1) { return true; }
```

**Comment by jacobp100** [comment]
Thanks for looking into that. I’m not sure on checking for the extension in get-es-imports, since that isn’t tied to es-css-modules. However, I think I might have seen a bug that could have caused this (https://github.com/jacobp100/es-css-modules/commit/6a1a85a7956d5da9d6eb5f4857c87de4ef6a5a71).

Reckon I could get you to test again? :)

**Comment by aikeru** [comment]
Looking good! I even re-cloned the repo, npm install, gulp and then opened the index.html.

I wish we could all develop on *nix, but many of us work at "Windows" shops ...

![image](https://cloud.githubusercontent.com/assets/1163405/15807275/49e5f562-2b1f-11e6-84e9-05c33bc909ee.png)

I will close the issue! :)

**Comment by jacobp100** [comment]
Glad to hear it works now! Thanks a lot for helping out—very appreciated!
